---
services:
  no-authentication:
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - 6668:6668
  tls-authentication:
    image: ${DOCKER_IMAGE_NAME}
    volumes:
      - ./../../test_data:/data
    command: --tls-p12-file /data/client_server/server/kmserver.acme.com.p12 --tls-p12-password password --authority-cert-file /data/client_server/ca/ca.crt
    ports:
      - 6669:6669
