---
default: true

# default indent = 4 spaces
MD007:
  indent: 2
# MD030:
#     ul_single: 3
#     ul_multi: 3

MD024:
  # Allow heading duplication if under different parent headings
  siblings_only: true
