[package]
name = "findex-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4"
env_logger = "0.10"
cloudproof_findex = { git = "https://github.com/Cosmian/cloudproof_rust.git", branch = "fix/sync_findex_develop", features = ["backend-sqlite", "serialization"] }
cosmian_findex = { git = "https://github.com/Cosmian/findex", branch = "develop" }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
