[workspace]
default-members = ["crate/server", "crate/cli"]
members = [
  "crate/server",
  "crate/logger",
  "crate/client",
  "crate/cli",
  "crate/test_server",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"
authors = [
  "Emmanuel Coste<emmanuel.coste@cosmian.com>",
  "Hatem M'naouer <hatem.mnaouer@cosmian.com>",
]
license = "BUSL-1.1"
license-file = "LICENSE"
repository = "https://github.com/Cosmian/cosmian_findex_server"
keywords = ["findex", "cosmian"]
categories = ["security"]

[profile.release]
lto = true
strip = true

[profile.dev]
strip = "debuginfo"
incremental = false

# proc-macros and build-scripts
[profile.dev.build-override]
strip = "debuginfo"
incremental = false

# external dependencies
[profile.dev.package."*"]
opt-level = 0

[workspace.dependencies]
actix-server = { version = "2.5", default-features = false }
actix-web = { version = "4.9.0", default-features = false }
base64 = "0.21"
clap = { version = "4.5", default-features = false }
cloudproof_findex = { path = "../cloudproof_rust/crates/findex" }
# cloudproof_findex = { git = "https://www.github.com/Cosmian/cloudproof_rust", branch = "feat/add_basic_findex_rest_client" }
der = { version = "0.7", default-features = false }
openssl = { version = "0.10", default-features = false }
pem = "3.0"
reqwest = { version = "0.11", default-features = false }
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.40", default-features = false }
tracing = "0.1"
url = "2.5"
x509-parser = "0.16"
zeroize = { version = "1.8", default-features = false }
