[package]
name = "findex-server"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.9.0"
dotenv = "0.15.0"
env_logger = "0.11.5"
log = "0.4.22"
serde = {version = "1.0.210" ,  features = ["derive"] }
# TODO : will be added later, focus on auth first
# cloudproof_findex = { git = "https://github.com/Cosmian/cloudproof_rust.git", branch = "fix/sync_findex_develop", features = ["backend-sqlite", "serialization"] }
# cosmian_findex = { git = "https://github.com/Cosmian/findex", branch = "develop" }

