---
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 10s
      timeout: 5s
      retries: 5
  kms:
    container_name: kms
    # image: ghcr.io/cosmian/kms:4.22.1
    image: ghcr.io/cosmian/kms:feat-add_digest_and_mac_kmip_operations
    ports:
      - 9998:9998
