#!/bin/sh

systemctl daemon-reload

# Check if the service is active (running)
if systemctl is-active --quiet cosmian_findex_server.service; then
  echo "Service is running. Stopping the service..."
  systemctl stop cosmian_findex_server.service

  # Verify if the service was stopped
  if systemctl is-active --quiet cosmian_findex_server.service; then
    echo "Failed to stop the service."
  else
    echo "Service stopped successfully. Disabling it"
    if systemctl list-unit-files | grep -q '^cosmian_findex_server.service'; then
      echo "Service exists. Disabling the service..."
      systemctl disable cosmian_findex_server.service
    fi
  fi
else
  echo "Service is not running. Disabling it"
  if systemctl list-unit-files | grep -q '^cosmian_findex_server.service'; then
    echo "Service exists. Disabling the service..."
    systemctl disable cosmian_findex_server.service
  fi
fi

systemctl daemon-reload

#DEBHELPER#
