[package]
name = "cosmian_findex_structs"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
# doc test linking as a separate binary is extremely slow
# and is not needed for internal lib
doctest = false

[features]

[dependencies]
base64 = { workspace = true }
cloudproof_findex = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
cosmian_crypto_core = { workspace = true, features = ["ser"] }
cosmian_findex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rmp-serde = "1.3.0"
cosmian_findex_config = { path = "../config" }
serde_bytes = "0.11.15"
rand = "0.8.5"
