---
name: Findex server cargo build - windows

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      archive-name:
        required: true
        type: string
      debug_or_release:
        required: true
        type: string

jobs:
  findex-server-build:
    name: ${{ inputs.archive-name }}
    runs-on: windows-2022
    steps:
      - name: Print ENV
        run: printenv

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
          components: rustfmt, clippy

      # - name: Discover dumpbin location
      #   shell: pwsh
      #   run: |
      #     Get-ChildItem -Recurse "C:\Program Files\Microsoft Visual Studio"

      - name: Discover environment variables on Runner
        shell: pwsh
        run: |
          Get-ChildItem env:

      - name: Locate VCPKG_INSTALLATION_ROOT
        shell: pwsh
        run: |
          Get-ChildItem $env:VCPKG_INSTALLATION_ROOT

      - name: Build static OpenSSL
        shell: pwsh
        run: |
          vcpkg install --triplet x64-windows-static
          vcpkg integrate install

          Get-ChildItem -Recurse "$env:VCPKG_INSTALLATION_ROOT\packages"

      - name: Build
        shell: pwsh
        run: |
          . .\.github\scripts\cargo_build.ps1
          BuildProject -BuildType ${{ inputs.debug_or_release }}
        env:
          # Google variables
          TEST_GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.TEST_GOOGLE_OAUTH_CLIENT_ID }}
          TEST_GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.TEST_GOOGLE_OAUTH_CLIENT_SECRET }}
          TEST_GOOGLE_OAUTH_REFRESH_TOKEN: ${{ secrets.TEST_GOOGLE_OAUTH_REFRESH_TOKEN }}

      - name: Upload Findex server for windows-2022
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.archive-name }}-${{ inputs.debug_or_release }}
          path: |
            target/x86_64-pc-windows-msvc/${{ inputs.debug_or_release }}/cosmian.exe
            target/x86_64-pc-windows-msvc/${{ inputs.debug_or_release }}/cosmian_findex_server.exe
          retention-days: 1
          if-no-files-found: error

  findex-server-test:
    needs: findex-server-build
    name: Clean env. ${{ inputs.archive-name }}
    runs-on: windows-2022
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.archive-name }}-${{ inputs.debug_or_release }}

      - name: List files recursively
        shell: pwsh
        run: Get-ChildItem -Recurse

      - name: Launch cosmian and cosmian_findex_server
        run: |
          pwd
          ./cosmian.exe -V
          ./cosmian_findex_server.exe -V
