---
name: Build all

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      debug_or_release:
        required: true
        type: string

jobs:
  rhel9:
    name: RHEL9
    uses: ./.github/workflows/build_rhel9.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      archive-name: rhel9
      target: x86_64-unknown-linux-gnu
      debug_or_release: ${{ inputs.debug_or_release }}

  generic-linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - distribution: ubuntu-22.04
            archive-name: ubuntu_22_04
            target: x86_64-unknown-linux-gnu
          - distribution: ubuntu-24.04
            archive-name: ubuntu_24_04
            target: x86_64-unknown-linux-gnu
    name: ${{ matrix.distribution }}
    uses: ./.github/workflows/build_generic.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      distribution: ${{ matrix.distribution }}
      archive-name: ${{ matrix.archive-name }}
      target: ${{ matrix.target }}
      debug_or_release: ${{ inputs.debug_or_release }}
      docker_compose: true

  generic-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - distribution: macos-14
            archive-name: macos_arm
            target: aarch64-apple-darwin
    name: ${{ matrix.distribution }}
    uses: ./.github/workflows/build_generic.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      distribution: ${{ matrix.distribution }}
      archive-name: ${{ matrix.archive-name }}
      target: ${{ matrix.target }}
      debug_or_release: ${{ inputs.debug_or_release }}
      skip_services_tests: --skip test_findex --skip test_all_authentications --skip test_server_auth_matrix --skip test_datasets --skip test_permissions
        --skip memory_adt

  windows-2022:
    if: inputs.debug_or_release == 'release'
    uses: ./.github/workflows/build_windows.yml
    with:
      toolchain: ${{ inputs.toolchain }}
      archive-name: windows
      debug_or_release: ${{ inputs.debug_or_release }}

  cleanup:
    needs:
      - rhel9
      - generic-linux
      - generic-macos
      - windows-2022
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@develop
    secrets: inherit
