---
name: cargo build - no docker

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      distribution:
        required: true
        type: string
      archive-name:
        required: true
        type: string
      target:
        required: true
        type: string
      debug_or_release:
        required: true
        type: string
      skip_services_tests:
        required: false
        type: string
      docker_compose:
        required: false
        type: boolean
        default: false

jobs:
  cargo-build:
    name: ${{ inputs.archive-name }}
    runs-on: ${{ inputs.distribution }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
          components: rustfmt, clippy

      - name: Run Redis container
        if: ${{ inputs.docker_compose }}
        run: |
          docker compose -h
          docker compose up -d

      - name: Build and tests
        env:
          REDIS_URL: redis://localhost:6379
          REDIS_URL2: redis://localhost:6380

          # Google variables
          TEST_GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.TEST_GOOGLE_OAUTH_CLIENT_ID }}
          TEST_GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.TEST_GOOGLE_OAUTH_CLIENT_SECRET }}
          TEST_GOOGLE_OAUTH_REFRESH_TOKEN: ${{ secrets.TEST_GOOGLE_OAUTH_REFRESH_TOKEN }}

          TARGET: ${{ inputs.target }}
          DEBUG_OR_RELEASE: ${{ inputs.debug_or_release }}
          SKIP_SERVICES_TESTS: ${{ inputs.skip_services_tests }}
        run: |
          bash .github/scripts/cargo_build.sh

      - name: Upload findex-server for ${{ inputs.distribution }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.archive-name }}-${{ inputs.debug_or_release }}
          path: |
            target/${{ inputs.target }}/${{ inputs.debug_or_release }}/cosmian_findex_cli
            target/${{ inputs.target }}/${{ inputs.debug_or_release }}/cosmian_findex_server
            target/${{ inputs.target }}/debian/*.deb
          retention-days: 1
          if-no-files-found: error

  test:
    needs: cargo-build
    name: Clean env. ${{ inputs.archive-name }}
    runs-on: ${{ inputs.distribution }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.archive-name }}-${{ inputs.debug_or_release }}

      - run: find .
        if: contains(runner.os, 'linux')

      - name: Linux launch cli and server
        if: contains(runner.os, 'Linux')
        run: |
          set -ex
          pwd
          find . -type f
          chmod u+x ./${{ inputs.debug_or_release }}/cosmian_findex_cli
          chmod u+x ./${{ inputs.debug_or_release }}/cosmian_findex_server

          ./${{ inputs.debug_or_release }}/cosmian_findex_cli -V
          ./${{ inputs.debug_or_release }}/cosmian_findex_server -V

      - name: MacOS launch cli and server
        if: contains(runner.os, 'macos')
        run: |
          set -ex
          chmod u+x ./${{ inputs.debug_or_release }}/cosmian_findex_cli
          chmod u+x ./${{ inputs.debug_or_release }}/cosmian_findex_server

          ./${{ inputs.debug_or_release }}/cosmian_findex_cli -V
          ./${{ inputs.debug_or_release }}/cosmian_findex_server -V
