---
name: Docker build

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      registry-image:
        required: true
        type: string
      platforms:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    name: Image
    uses: Cosmian/reusable_workflows/.github/workflows/build_docker_image.yml@dadd-workflows
    secrets: inherit
