---
name: Docker build

on:
  workflow_call:
    inputs:
      prefix:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      registry-image:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    name: ${{ inputs.prefix }} Image
    runs-on: ubuntu-22.04
    container: docker:19.03.15

    steps:
      - name: Display cpuinfo
        run: cat /proc/cpuinfo

      - name: Install tar
        run: apk add --no-cache tar

      - uses: actions/checkout@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ inputs.registry-image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag docker container
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ inputs.dockerfile }}
          network: host

      - name: Display metadata version ${{ steps.meta.outputs.version }}
        run: |
          echo version: "${{ steps.meta.outputs.version }}"
          echo tags: "${{ steps.meta.outputs.tags }}"

    outputs:
      image-tag: ${{ inputs.registry-image }}:${{ steps.meta.outputs.version }}
