---
name: Cargo lint

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache dependencies
        id: cargo_cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check --color always

      - name: Static analysis
        run: cargo clippy --workspace --all-targets --all-features --tests -- -D warnings
