---
name: CI checks

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      debug_or_release:
        required: true
        type: string
      platforms:
        required: true
        type: string

jobs:
  cargo-clippy:
    uses: Cosmian/reusable_workflows/.github/workflows/clippy.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}

  cargo-deny:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-audit.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}

  cargo-machete:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-machete.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}

  # ml-kem-0.2.1 does not build on toolchain 1.90.0 and cargo-semver v0.44.0.
  # cargo-semver:
  #   uses: Cosmian/reusable_workflows/.github/workflows/cargo-semver.yml@develop
  #   with:
  #     toolchain: ${{ inputs.toolchain }}

  build-tests:
    uses: Cosmian/reusable_workflows/.github/workflows/build_all.yml@develop
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      debug_or_release: ${{ inputs.debug_or_release }}

  cargo-publish:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-publish-workspace.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}
    secrets:
      token: ${{ secrets.CRATES_IO }}

  docker-image:
    name: Build docker image
    uses: Cosmian/reusable_workflows/.github/workflows/build_docker_image.yml@develop
    with:
      prefix: ''
      registry-image: ghcr.io/cosmian/findex-server
      platforms: ${{ inputs.platforms }}

  ##############################################################################
  ### Releases
  ##############################################################################
  push-artifacts:
    needs:
      - cargo-clippy
      - cargo-deny
      - cargo-machete
      - build-tests
    uses: Cosmian/reusable_workflows/.github/workflows/push-artifacts.yml@develop
    with:
      project-name: findex-server
      destination: findex-server
      debug_or_release: ${{ inputs.debug_or_release }}

  public_documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Deploy documentation in staging
        if: ${{ github.ref_name == 'develop' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: staging.yml
          repo: Cosmian/public_documentation
          ref: develop
          token: ${{ secrets.PAT_TOKEN }}

      - name: Deploy documentation in prod
        if: startsWith(github.ref, 'refs/tags')
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: prod.yml
          repo: Cosmian/public_documentation
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
