---
name: CI checks

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      debug_or_release:
        required: true
        type: string

jobs:
  cargo-lint:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-nursery-base.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}

  build-tests:
    uses: Cosmian/reusable_workflows/.github/workflows/build_all.yml@develop
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      debug_or_release: ${{ inputs.debug_or_release }}

  docker-image-release:
    if: inputs.debug_or_release == 'release'
    name: Build docker image for AMD64 and ARM64
    uses: Cosmian/reusable_workflows/.github/workflows/build_docker_image.yml@develop
    with:
      prefix: ''
      registry-image: ghcr.io/cosmian/findex-server
      platforms: linux/amd64,linux/arm64

  docker-image:
    if: inputs.debug_or_release == 'debug'
    name: Build docker image for AMD64
    uses: Cosmian/reusable_workflows/.github/workflows/build_docker_image.yml@develop
    with:
      prefix: ''
      registry-image: ghcr.io/cosmian/findex-server
      platforms: linux/amd64

  ##############################################################################
  ### Releases
  ##############################################################################
  push-artifacts:
    needs:
      - cargo-lint
      - build-tests
    uses: Cosmian/reusable_workflows/.github/workflows/push-artifacts.yml@develop
    with:
      project-name: findex-server
      destination: findex-server
      debug_or_release: ${{ inputs.debug_or_release }}

  cargo-publish:
    needs:
      - cargo-lint
      - build-tests
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-publish-workspace.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}
    secrets:
      token: ${{ secrets.CRATES_IO }}

  public_documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Deploy documentation in staging
        if: ${{ github.ref_name == 'develop' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: staging.yml
          repo: Cosmian/public_documentation
          ref: develop
          token: ${{ secrets.PAT_TOKEN }}

      - name: Deploy documentation in prod
        if: startsWith(github.ref, 'refs/tags')
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: prod.yml
          repo: Cosmian/public_documentation
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
