---
name: CI debug

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  main:
    secrets: inherit
    uses: ./.github/workflows/main_base.yml
    with:
      toolchain: 1.90.0
      debug_or_release: debug
      platforms: linux/amd64
